Updating

diff --git a/atom-editor-sync/PKGBUILD b/atom-editor-sync/PKGBUILD
--- a/atom-editor-sync/PKGBUILD
+++ b/atom-editor-sync/PKGBUILD
@@ -2,6 +2,16 @@
 
 _pkgname=atom
 _version=sync
+
+# Module Versions
+_about_ver=1.4.2
+_about_arch_ver=1.5.6
+_language_gfm_ver=0.85.0
+_language_gfm2_ver=0.89.1
+_language_liquid_ver=0.5.1
+_package_generator_ver=1.0.0
+_package_sync_ver=1.1.0
+
 pkgname=${_pkgname}-editor-${_version}
 pkgver=1.7.4
 pkgrel=6
@@ -27,10 +37,18 @@ prepare() {
   sed -i -e "/exception-reporting/d" \
 	       -e "/metrics/d" \
          -e 's/0.36.8/0.36.12/g' \
-         -e 's/"language-gfm": "0.85.0",/"language-gfm2": "0.88.2",\n    "language-liquid": "0.5.1",/g' \
-         -e 's/"package-generator": "1.0.0",/"package-generator": "1.0.0",\n    "package-sync": "1.1.0",/g' package.json
+         -e "s/\"language-gfm\": \"${_language_gfm_ver}\",/\"language-gfm2\": \"${_language_gfm2_ver}\",\n    \"language-liquid\": \"${_language_liquid_ver}\",/g" \
+         -e "s/\"about\": \"${_about_ver}\"/\"about-arch\": \"${_about_arch_ver}\"/g" \
+         -e "s/\"package-generator\": \"${_package_generator_ver}\",/\"package-generator\": \"${_package_generator_ver}\",\n    \"package-sync\": \"${_package_sync_ver}\",/g" package.json
 
   chmod 755 -R package.json
+
+  if ! [[ -d node_modules ]]; then
+    mkdir node_modules
+  fi
+
+  sed -i -e 's@node script/bootstrap@node script/bootstrap --no-quiet@g' \
+  ./script/build || die "Fail fixing verbosity of script/build"
 
   sed -i -e "s/<%=Desc=%>/$pkgdesc/g" ${srcdir}/${_pkgname}-${_version}.desktop
 }
