Updating

diff --git a/atom-editor-fusion/PKGBUILD b/atom-editor-fusion/PKGBUILD
--- a/atom-editor-fusion/PKGBUILD
+++ b/atom-editor-fusion/PKGBUILD
@@ -17,7 +17,7 @@ _language_d_ver=3.2.3
 _language_docker_ver=1.1.6
 _language_fortran_ver=2.0.11
 _language_gentoo_ver=0.9.0
-_language_gfm2_ver=0.90.2
+_language_gfm2_ver=0.90.3
 _language_groovy_ver=0.6.0
 _language_haskell_ver=1.7.15
 _language_ini2_ver=1.17.2
@@ -27,32 +27,10 @@ _language_lisp_ver=0.2.0
 _language_lua_ver=0.9.4
 _language_matlab_ver=0.2.1
 _language_pascal_ver=0.18.1
+_language_rpm_spec_ver=0.9.0
+_rpm_spec_url="https://github.com/waveclaw/language-rpm-spec"
 _language_viml_ver=1.0.0
 _language_shellscript_ver=0.22.3
-_linter_ver=1.11.4
-_linter_clojure_ver=1.1.2
-_linter_coffeelint_ver=1.1.2
-_linter_cpplint_ver=1.0.1
-_linter_csslint_ver=1.3.2
-_linter_docker_ver=0.1.2
-_linter_golinter_ver=1.2.0
-_linter_htmlhint_ver=1.1.4
-_linter_javac_ver=1.9.3
-_linter_jshint_ver=2.1.0
-_linter_jsonlint_ver=1.2.5
-_linter_lua_ver=1.0.2
-_linter_markdown_ver=1.5.2
-_linter_php_ver=1.2.0
-_linter_pylint_ver=1.2.0
-_linter_ruby_ver=1.2.2
-_linter_rust_ver=0.4.6
-_linter_sass_lint_ver=1.5.0
-_linter_scalac_ver=1.4.0
-_linter_scss_lint_ver=3.0.4
-_linter_shellcheck_ver=1.2.0
-_linter_tslint_ver=0.10.0
-_linter_twig_ver=0.1.1
-_minimap_linter_ver=1.1.1
 _markdown_scroll_sync_ver=2.1.2
 _markdown_toc_ver=0.4.1
 _minimap_ver=4.24.3
@@ -64,7 +42,7 @@ _platformio_ide_terminal_ver=2.0.10
 
 pkgname=${_pkgname}-editor-${_version}
 pkgver=1.7.4
-pkgrel=8
+pkgrel=9
 pkgdesc='Hackable text editor for the 21st Century, based on web technologies with several custom packages installed.'
 arch=('x86_64' 'i686')
 url="https://github.com/${_pkgname}/${_pkgname}"
@@ -76,11 +54,14 @@ conflicts=('atom-editor-bin' 'atom-editor')
 install=${_pkgname}-${_version}.install
 source=("${_pkgname}-${pkgver}.tar.gz::$url/archive/v${pkgver}.tar.gz"
 "about-arch-${_about_arch_ver}.tar.gz::$_about_url/archive/v${_about_arch_ver}.tar.gz"
+"rpm-spec-${_language_rpm_spec_ver}.tar.gz::${_rpm_spec_url}/archive/v${_language_rpm_spec_ver}.tar.gz"
+"git+https://github.com/skandasoft/browser-plus.git"
 "${_pkgname}.desktop"
 "${_pkgname}")
 sha256sums=('6ef3bb4c2fea85a7d1c7665fef8aac4e353c8f8da5e2878fea3aecf5437383d4'
-            'de170455e00c684c452acdda5dbfa1182370cd2025990f944bfa48e0df685c6d'
-            'c79258854e573dd290aa88323e4ef916acc261b224c1b6df16451fe0b955d4b1'
+            '1f9d3d560ab6374b38644e9c55a7c8fa0f8f581758fb2ee0b18c3f8c53aee44f'
+            'e238bc5ac98da32057c9df5e7710b42c8cdd2bab13a9961c5dffdffbfcb2ea2c'
+            'SKIP'
             'fb6527d029c5edffa89a5085cc1d3eaaa892e18cc2aefa8ce855be7612da4788'
             '0b3e189202c82c98bc3d3f9a9c88d2aab88537cdd2e0fc2f4d537f55a068acb5')
 
@@ -89,7 +70,7 @@ prepare() {
 
   ## package.json edits
   sed -i -e "/exception-reporting/d" \
-           -e "/metrics/d" package.json
+         -e "/metrics/d" package.json
 
   sed -i -e "s/\"about\": \".*\"/\"about-arch\": \"${_about_arch_ver}\"/g" package.json # switching about with about-arch
 
@@ -132,31 +113,54 @@ prepare() {
 
   sed -i -e "s/\"language-shellscript\": \".*\"/\"language-shellscript\": \"${_language_shellscript_ver}\"/g" package.json
 
+  sed -i -e "/\"language-shellscript\": \".*\",/i \
+              \"language-rpm-spec\": \"${_language_rpm_spec_ver}\"," package.json
+
   sed -i -e "/\"package-generator\": \".*\",/a \
               \"package-sync\": \"${_package_sync_ver}\",\n    \"pigments\": \"${_pigments_ver}\",\n    \"script\": \"${_script_ver}\",\n    \"platformio-ide-terminal\": \"${_platformio_ide_terminal_ver}\"," package.json
 
   sed -i -e "/\"markdown-preview\": \".*\",/a \
               \"markdown-scroll-sync\": \"${_markdown_scroll_sync_ver}\",\n    \"markdown-toc\": \"${_markdown_toc_ver}\",\n    \"minimap\": \"${_minimap_ver}\"," package.json
 
-  ##sed -i -e "/\"link\": \".*\",/a \
-  ##            \"linter\": \"${_linter_ver}\",\n    \"linter-clojure\": \"${_linter_clojure_ver}\",\n    \"linter-coffeelint\": \"${_linter_coffeelint_ver}\",\n    \"linter-cpplint\": \"${_linter_cpplint_ver}\",\n    \"linter-csslint\": \"${_linter_csslint_ver}\",\n    \"linter-docker\": \"${_linter_docker_ver}\",\n    \"linter-golinter\": \"${_linter_golinter_ver}\",\n    \"linter-htmlhint\": \"${_linter_htmlhint_ver}\",\n    \"linter-javac\": \"${_linter_javac_ver}\",\n    \"linter-jshint\": \"${_linter_jshint_ver}\",\n    \"linter-jsonlint\": \"${_linter_jsonlint_ver}\",\n    \"linter-lua\": \"${_linter_lua_ver}\",\n    \"linter-markdown\": \"${_linter_markdown_ver}\",\n    \"linter-php\": \"${_linter_php_ver}\",\n    \"linter-pylint\": \"${_linter_pylint_ver}\",\n    \"linter-ruby\": \"${_linter_ruby_ver}\",\n    \"linter-rust\": \"${_linter_rust_ver}\",\n    \"linter-scalac\": \"${_linter_scalac_ver}\",\n    \"linter-shellcheck\": \"${_linter_shellcheck_ver}\",\n    \"linter-sass-lint\": \"${_linter_sass_lint_ver}\",\n    \"linter-scss-lint\": \"${_linter_scss_lint_ver}\",\n    \"linter-tslint\": \"${_linter_tslint_ver}\",\n    \"linter-twig\": \"${_linter_twig_ver}\"," package.json
+ sed -i -e "/\"bracket-matcher\": \".*\",/a \
+              \"browser-plus\": \"0.0.60\"," package.json
 
-  sed -i -e "s|^\"|    \"|g"  package.json # fixing spacing issues
+ sed -i -e "s|^\"|    \"|g"  package.json # fixing spacing issues
 
-  chmod 755 -R package.json
+ chmod 755 -R package.json
 
-  sed -i -e 's@node script/bootstrap@node script/bootstrap --no-quiet@g' \
-  ./script/build || die "Fail fixing verbosity of script/build"
+ sed -i -e 's@node script/bootstrap@node script/bootstrap --no-quiet@g' \
+ ./script/build || die "Fail fixing verbosity of script/build"
 
-  if ! [[ -d node_modules ]]; then
-    mkdir -p node_modules
-  else
-    rm -rf node_modules/about-arch
-  fi
+ if ! [[ -d node_modules ]]; then
+  mkdir -p node_modules
+ else
+   rm -rf node_modules/about-arch
+   rm -rf node_modules/browser-plus
+   rm -rf node_modules/language-rpm-spec
+ fi
 
   mv $srcdir/about-${_about_arch_ver} $srcdir/about-arch
   mv $srcdir/about-arch node_modules
   sed -i -e "s/atom-editor/atom-editor-${_version}/g" node_modules/about-arch/lib/about-view.coffee
+
+  mv $srcdir/browser-plus node_modules
+
+  sed -i -e "/\"name\": \"browser-plus\",/a \
+              \"readme\": \"./README.md\"," node_modules/browser-plus/package.json
+
+  cd node_modules/browser-plus
+  npm install
+  cd -
+
+  # language-rpm-spec
+  mv $srcdir/language-rpm-spec-${_language_rpm_spec_ver} $srcdir/language-rpm-spec
+  mv $srcdir/language-rpm-spec node_modules
+
+  sed -i -e "s|\"language-rpm-spec\",|\"language-rpm-spec\",\n  \"readme\": \"./README.md\",|g" \
+  node_modules/language-rpm-spec/package.json
+
+  sed -i -e "/main/d" node_modules/language-rpm-spec/package.json
 
   sed -i -e "s/<%=Desc=%>/$pkgdesc/g" ${srcdir}/${_pkgname}.desktop
 }
